title:              zombiedogz
description:        Testing and Development of Zombie bits.
url:                "https://zombiedogz.github.io"
baseurl:            "/"


# Social Profiles
twitter_username:   zombiedogz
github_username:    zombiedogz

# Prebuilt Themes
theme:             jekyll-theme-cayman


# default settings
# defaults:
#  - scope:
#      path: ""
#    values:
#      layout: default


# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
